apiVersion: v1
baseDomain: ziiot.ru
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 3 
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3 
metadata: 
  name: okd-yc
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}' 
sshKey: **
